subroutine tbf90(Tb,I01p,T,incAng,k,a,g,n,eps,dz)
  implicit none
  real :: incAng, eps, dz
  integer :: n
  real, intent(out) ::Tb
  real :: k(n+1), a(n+1), g(n+1)
  real :: I01p(2*n+3)
  real :: Jup(n+1), Jd(n+1), T(n+1)
  real :: cos1
  real :: intDo(n+1)
  real :: intUp(n+1)
  real :: pi, sumJD, sumJU
  integer :: k1, i

  pi=3.1415
  
  Jd=0.
  Jup=0.

  cos1=cos(incAng/180.*pi)
  do k1=1,n+1
     Jup(k1)=(1-a(k1))*T(k1)+a(k1)*(0.5*(I01p(2*k1-1)+I01p(2*k1+1))*g(k1)*cos1+I01p(2*k1))
     Jd(k1)=(1-a(k1))*T(k1)+a(k1)*(-0.5*(I01p(2*k1-1)+I01p(2*k1+1))*g(k1)*cos1+I01p(2*k1))
  end do
  
  intDo(1)=k(1)*dz/2
  intUp(n+1)=k(n+1)*dz/2
  do k1=1,n
     intUp(n+1-k1)=intUp(n-k1+2)+0.5*(k(n+1-k1)+k(n+1-k1+1))*dz
  end do
  
  do k1=2,n+1
     intDo(k1)=intDo(k1-1)+0.5*(k(k1)+k(k1-1))*dz
  end do
  sumJD=0.
  sumJU=0.
  do i=1,n+1
     sumJD=sumJD+Jd(i)*exp(-intDo(i)/cos1)*k(i)*dz/cos1
     sumJU=sumJU+Jup(i)*exp(-intUp(i)/cos1)*k(i)*dz/cos1
  end do
!  print*, 'jd=',sumJD
!  print*, 'ju=',sumJU
!  print*, eps, exp(-intUp(1)), T(1)
  Tb=(1-eps)*exp(-intUp(1)/cos1)*sumJD+sumJU+eps*exp(-intUp(1)/cos1)*T(1)
  
end subroutine tbf90


subroutine yTtimesA(doty,y,Ainv,n)
  implicit none
  integer :: n, i, j
  real :: y(2*n+3), Ainv(2*n+3,2*n+3)
  real, intent(out) :: doty(2*n+3)
  do j=1,2*n+3
     doty(j)=0
     do i=1,2*n+3
        doty(j)= doty(j)+y(i)*Ainv(i,j)
     enddo
  enddo
end subroutine yTtimesA
subroutine suml1B(y,lam1, k,a,g,n,T,eps,dz)
  implicit none
  integer :: n
  real :: y, lam1(2*n+3), lam2(2*n+3), k(n+1), a(n+1), g(n+1), T(n+1),dz,eps
  real  B(2*n+3), am, km, gm
  integer ::  i

  y=0

  do i=0,n
     B(2*i+2)=3*k(i+1)*(1-a(i+1))*T(i+1)*dz
     y=y+B(2*i+2)*lam1(2*i+2)
  enddo

end subroutine suml1B

subroutine suml1Al2(y,lam1,lam2, k,a,g,n,T,eps,dz)
  implicit none
  integer :: n
  real :: y, lam1(2*n+3), lam2(2*n+3), k(n+1), a(n+1), g(n+1), T(n+1),dz,eps
  real  Abig(2*n+3,2*n+3), am, km, gm
  integer ::  i
  y=0
  
  do i=0,n
     Abig(2*i+2,2*i+2)=3*k(i+1)*(1-a(i+1))*dz
     Abig(2*i+2,2*i+3)=1
     Abig(2*i+2,2*i+1)=-1
     y=y+Abig(2*i+2,2*i+2)*lam1(2*i+2)*lam2(2*i+2)
     y=y+Abig(2*i+2,2*i+3)*lam1(2*i+2)*lam2(2*i+3)
     y=y+Abig(2*i+2,2*i+1)*lam1(2*i+2)*lam2(2*i+1)
     if(2*i+3<2*n+3) then
        km=0.5*(k(i+1)+k(i+2))
        am=0.5*(a(i+1)+a(i+2))
        gm=0.5*(g(i+1)+g(i+2))
        Abig(2*i+3,2*i+3)=km*(1-am*gm)*dz
        Abig(2*i+3,2*i+4)=1
        Abig(2*i+3,2*i+2)=-1
        y=y+Abig(2*i+3,2*i+3)*lam1(2*i+3)*lam2(2*i+3)
        y=y+Abig(2*i+3,2*i+4)*lam1(2*i+3)*lam2(2*i+4)
        y=y+Abig(2*i+3,2*i+2)*lam1(2*i+3)*lam2(2*i+2)
     endif
  enddo
  Abig(2*n+3,2*n+2)=1.
  Abig(2*n+3,2*n+3)=-1./3
  Abig(2*n+3,2*n+1)=-1./3
  
  y=y+Abig(2*n+3,2*n+2)*lam1(2*n+3)*lam2(2*n+2)
  y=y+Abig(2*n+3,2*n+3)*lam1(2*n+3)*lam2(2*n+3)
  y=y+Abig(2*n+3,2*n+1)*lam1(2*n+3)*lam2(2*n+1)

  Abig(1,1)=(2-eps)/3./eps
  Abig(1,2)=1.
  Abig(1,3)=(2-eps)/3./eps
  
  y=y+Abig(1,1)*lam1(1)*lam2(1)
  y=y+Abig(1,2)*lam1(1)*lam2(2)
  y=y+Abig(1,3)*lam1(1)*lam2(3)

end subroutine suml1Al2

subroutine SetEddington1D(k,a,g,Abig,B,T,n,eps,dz,Ts)
  implicit none
  integer :: n
  real, intent(out) :: Abig(2*n+3,2*n+3), B(2*n+3)
  real,intent(in) ::    T(n+1),k(n+1),a(n+1),g(n+1), dz
  real :: am, gm, km, eps, Ts
  integer :: i
  !dz=0.25
  Abig=0
  do i=0,n
     Abig(2*i+2,2*i+2)=+3*k(i+1)*(1-a(i+1))*dz
     Abig(2*i+2,2*i+3)=1
     Abig(2*i+2,2*i+1)=-1
     B(2*i+2)=3*k(i+1)*(1-a(i+1))*T(i+1)*dz
     if(2*i+3<2*n+3) then
        km=0.5*(k(i+1)+k(i+2))
        am=0.5*(a(i+1)+a(i+2))
        gm=0.5*(g(i+1)+g(i+2))
        Abig(2*i+3,2*i+3)=km*(1-am*gm)*dz
        Abig(2*i+3,2*i+4)=1
        Abig(2*i+3,2*i+2)=-1
        B(2*i+3)=0.
     endif
  enddo
  Abig(2*n+3,2*n+2)=1.
  Abig(2*n+3,2*n+3)=-1./3
  Abig(2*n+3,2*n+1)=-1./3
  B(2*n+3)=2.7
  Abig(1,1)=(2-eps)/3./eps
  Abig(1,2)=1.
  Abig(1,3)=(2-eps)/3./eps
  B(1)=Ts
end subroutine SetEddington1D

!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.10 (r5363) -  9 Sep 2014 09:54
!
!  Differentiation of suml1al2 in reverse (adjoint) mode:
!   gradient     of useful results: y
!   with respect to varying inputs: g k y a
!   RW status of diff variables: g:out k:out y:in-zero a:out

SUBROUTINE SUML1AL2_B(y, yb, lam1, lam2, k, kb, a, ab, g, gb, n, t, eps&
& , dz)
  IMPLICIT NONE
  INTEGER :: n
  REAL :: y, lam1(2*n+3), lam2(2*n+3), k(n+1), a(n+1), g(n+1), t(n+1), &
& dz, eps
  REAL :: yb
  real, intent(out) :: kb(n+1), ab(n+1), gb(n+1)
  REAL :: abig(2*n+3, 2*n+3), am, km, gm
  REAL :: abigb(2*n+3, 2*n+3), amb, kmb, gmb
  INTEGER :: i
  INTEGER :: branch
  REAL :: tempb0
  REAL :: tempb

  abigb = 0.0
  abigb(1, 3) = abigb(1, 3) + lam1(1)*lam2(3)*yb
  abigb(1, 2) = abigb(1, 2) + lam1(1)*lam2(2)*yb
  abigb(1, 1) = abigb(1, 1) + lam1(1)*lam2(1)*yb
  abigb(1, 3) = 0.0
  abigb(1, 2) = 0.0
  abigb(1, 1) = 0.0
  abigb(2*n+3, 2*n+1) = abigb(2*n+3, 2*n+1) + lam1(2*n+3)*lam2(2*n+1)*yb
  abigb(2*n+3, 2*n+3) = abigb(2*n+3, 2*n+3) + lam1(2*n+3)*lam2(2*n+3)*yb
  abigb(2*n+3, 2*n+2) = abigb(2*n+3, 2*n+2) + lam1(2*n+3)*lam2(2*n+2)*yb
  abigb(2*n+3, 2*n+1) = 0.0
  abigb(2*n+3, 2*n+3) = 0.0
  abigb(2*n+3, 2*n+2) = 0.0
  gb = 0.0
  kb = 0.0
  ab = 0.0
  DO i=n,0,-1

    IF (2*i+3 < 2*n+3) THEN
      abigb(2*i+3, 2*i+2) = abigb(2*i+3, 2*i+2) + lam1(2*i+3)*lam2(2*i+2&
&       )*yb
      abigb(2*i+3, 2*i+4) = abigb(2*i+3, 2*i+4) + lam1(2*i+3)*lam2(2*i+4&
&       )*yb
      abigb(2*i+3, 2*i+3) = abigb(2*i+3, 2*i+3) + lam1(2*i+3)*lam2(2*i+3&
&       )*yb
      abigb(2*i+3, 2*i+2) = 0.0
      abigb(2*i+3, 2*i+4) = 0.0
      gm = 0.5*(g(i+1)+g(i+2))
      am = 0.5*(a(i+1)+a(i+2))
      km = 0.5*(k(i+1)+k(i+2))
      tempb0 = dz*abigb(2*i+3, 2*i+3)
      kmb = (1-am*gm)*tempb0
      amb = -(km*gm*tempb0)
      gmb = -(km*am*tempb0)
      abigb(2*i+3, 2*i+3) = 0.0
      gb(i+1) = gb(i+1) + 0.5*gmb
      gb(i+2) = gb(i+2) + 0.5*gmb
      ab(i+1) = ab(i+1) + 0.5*amb
      ab(i+2) = ab(i+2) + 0.5*amb
      kb(i+1) = kb(i+1) + 0.5*kmb
      kb(i+2) = kb(i+2) + 0.5*kmb
    END IF
    abigb(2*i+2, 2*i+1) = abigb(2*i+2, 2*i+1) + lam1(2*i+2)*lam2(2*i+1)*&
&     yb
    abigb(2*i+2, 2*i+3) = abigb(2*i+2, 2*i+3) + lam1(2*i+2)*lam2(2*i+3)*&
&     yb
    abigb(2*i+2, 2*i+2) = abigb(2*i+2, 2*i+2) + lam1(2*i+2)*lam2(2*i+2)*&
&     yb
    abigb(2*i+2, 2*i+1) = 0.0
    abigb(2*i+2, 2*i+3) = 0.0
    tempb = dz*3*abigb(2*i+2, 2*i+2)
    kb(i+1) = kb(i+1) + (1-a(i+1))*tempb
    ab(i+1) = ab(i+1) - k(i+1)*tempb
    abigb(2*i+2, 2*i+2) = 0.0
  END DO
  yb = 0.0
END SUBROUTINE SUML1AL2_B

SUBROUTINE SUML1B_B(y, yb, lam1, k, kb, a, ab, g, n, t, eps, dz)
  IMPLICIT NONE
  INTEGER :: n
  REAL :: y, lam1(2*n+3), lam2(2*n+3), k(n+1), a(n+1), g(n+1), t(n+1), &
& dz, eps
  REAL :: yb 
  real, intent (out) :: kb(n+1), ab(n+1)
  REAL :: b(2*n+3), am, km, gm
  REAL :: bb(2*n+3)
  INTEGER :: i
  REAL :: tempb
  kb = 0.0
  ab = 0.0
  bb = 0.0
  DO i=n,0,-1
    bb(2*i+2) = bb(2*i+2) + lam1(2*i+2)*yb
    tempb = t(i+1)*dz*3*bb(2*i+2)
    kb(i+1) = kb(i+1) + (1-a(i+1))*tempb
    ab(i+1) = ab(i+1) - k(i+1)*tempb
    bb(2*i+2) = 0.0
  END DO
  yb = 0.0
END SUBROUTINE SUML1B_B

SUBROUTINE TBF90_B(tb, tbb, i01p, i01pb, t, incang, k, kb, a, ab, g, gb&
& , n, eps, dz)
  IMPLICIT NONE
  REAL :: incang, eps, dz
  INTEGER :: n
  REAL :: tb
  REAL :: tbb
  REAL :: k(n+1), a(n+1), g(n+1)
  REAL,intent(out) :: kb(n+1), ab(n+1), gb(n+1)
  REAL :: i01p(2*n+3)
  REAL, intent(out) :: i01pb(2*n+3)
  REAL :: jup(n+1), jd(n+1), t(n+1)
  REAL :: jupb(n+1), jdb(n+1)
  REAL :: cos1
  REAL :: intdo(n+1)
  REAL :: intdob(n+1)
  REAL :: intup(n+1)
  REAL :: intupb(n+1)
  REAL :: pi, sumjd, sumju
  REAL :: sumjdb, sumjub
  INTEGER :: k1, i
  INTRINSIC COS
  INTRINSIC EXP
  REAL :: temp
  REAL :: temp0
  REAL :: tempb
  REAL :: tempb0
  REAL :: temp1
  pi = 3.1415
  jd = 0.
  jup = 0.
  cos1 = COS(incang/180.*pi)
  DO k1=1,n+1
    jup(k1) = (1-a(k1))*t(k1) + a(k1)*(0.5*(i01p(2*k1-1)+i01p(2*k1+1))*g&
&     (k1)*cos1+i01p(2*k1))
    jd(k1) = (1-a(k1))*t(k1) + a(k1)*(-(0.5*(i01p(2*k1-1)+i01p(2*k1+1))*&
&     g(k1)*cos1)+i01p(2*k1))
  END DO
  intdo(1) = k(1)*dz/2
  intup(n+1) = k(n+1)*dz/2
  DO k1=1,n
    intup(n+1-k1) = intup(n-k1+2) + 0.5*(k(n+1-k1)+k(n+1-k1+1))*dz
  END DO
  DO k1=2,n+1
    intdo(k1) = intdo(k1-1) + 0.5*(k(k1)+k(k1-1))*dz
  END DO
  sumjd = 0.
  DO i=1,n+1
    sumjd = sumjd + jd(i)*EXP(-(intdo(i)/cos1))*k(i)*dz/cos1
  END DO
  intupb = 0.0
  temp1 = -(intup(1)/cos1)
  intupb(1) = intupb(1) - (EXP(temp1)*sumjd*(1-eps)/cos1+EXP(-(intup(1)/&
&   cos1))*eps*t(1)/cos1)*tbb
  sumjdb = EXP(temp1)*(1-eps)*tbb
  sumjub = tbb
  kb = 0.0
  intdob = 0.0
  jupb = 0.0
  jdb = 0.0
  DO i=n+1,1,-1
    temp1 = -(intup(i)/cos1)
    temp = jup(i)/cos1
    tempb = EXP(temp1)*dz*sumjub
    intupb(i) = intupb(i) - EXP(temp1)*temp*k(i)*dz*sumjub/cos1
    jupb(i) = jupb(i) + k(i)*tempb/cos1
    temp0 = -(intdo(i)/cos1)
    temp1 = jd(i)/cos1
    tempb0 = EXP(temp0)*dz*sumjdb
    kb(i) = kb(i) + temp*tempb + temp1*tempb0
    intdob(i) = intdob(i) - EXP(temp0)*temp1*k(i)*dz*sumjdb/cos1
    jdb(i) = jdb(i) + k(i)*tempb0/cos1
  END DO
  DO k1=n+1,2,-1
    intdob(k1-1) = intdob(k1-1) + intdob(k1)
    tempb = dz*0.5*intdob(k1)
    intdob(k1) = 0.0
    kb(k1) = kb(k1) + tempb
    kb(k1-1) = kb(k1-1) + tempb
  END DO
  DO k1=n,1,-1
    intupb(n-k1+2) = intupb(n-k1+2) + intupb(n+1-k1)
    tempb = dz*0.5*intupb(n+1-k1)
    intupb(n+1-k1) = 0.0
    kb(n+1-k1) = kb(n+1-k1) + tempb
    kb(n+1-k1+1) = kb(n+1-k1+1) + tempb
  END DO
  kb(n+1) = kb(n+1) + dz*intupb(n+1)/2
  kb(1) = kb(1) + dz*intdob(1)/2
  gb = 0.0
  i01pb = 0.0
  ab = 0.0
  DO k1=n+1,1,-1
    tempb = cos1*0.5*a(k1)*jupb(k1)
    temp = i01p(2*k1-1) + i01p(2*k1+1)
    temp0 = i01p(2*k1-1) + i01p(2*k1+1)
    ab(k1) = ab(k1) + (i01p(2*k1)-cos1*0.5*(temp0*g(k1))-t(k1))*jdb(k1) &
&     + (cos1*0.5*(temp*g(k1))+i01p(2*k1)-t(k1))*jupb(k1)
    i01pb(2*k1) = i01pb(2*k1) + a(k1)*jdb(k1) + a(k1)*jupb(k1)
    tempb0 = -(cos1*0.5*a(k1)*jdb(k1))
    jdb(k1) = 0.0
    i01pb(2*k1-1) = i01pb(2*k1-1) + g(k1)*tempb0 + g(k1)*tempb
    i01pb(2*k1+1) = i01pb(2*k1+1) + g(k1)*tempb0 + g(k1)*tempb
    gb(k1) = gb(k1) + temp0*tempb0 + temp*tempb
    jupb(k1) = 0.0
  END DO
END SUBROUTINE TBF90_B



SUBROUTINE TBF90_BI(tb, tbb, i01p, i01pb, t, incang, k, a, g, n, eps, dz)
  IMPLICIT NONE
  REAL :: incang, eps, dz
  INTEGER :: n
  REAL :: tb
  REAL :: tbb
  REAL :: k(n+1), a(n+1), g(n+1)
  REAL :: i01p(2*n+3)
  REAL,intent(out) :: i01pb(2*n+3)
  REAL :: jup(n+1), jd(n+1), t(n+1)
  REAL :: jupb(n+1), jdb(n+1)
  REAL :: cos1
  REAL :: intdo(n+1)
  REAL :: intup(n+1)
  REAL :: pi, sumjd, sumju
  REAL :: sumjdb, sumjub
  INTEGER :: k1, i
  INTRINSIC COS
  INTRINSIC EXP
  REAL :: tempb
  REAL :: tempb0
  pi = 3.1415
  cos1 = COS(incang/180.*pi)
  intdo(1) = k(1)*dz/2
  intup(n+1) = k(n+1)*dz/2
  DO k1=1,n
    intup(n+1-k1) = intup(n-k1+2) + 0.5*(k(n+1-k1)+k(n+1-k1+1))*dz
  END DO
  DO k1=2,n+1
    intdo(k1) = intdo(k1-1) + 0.5*(k(k1)+k(k1-1))*dz
  END DO
  sumjdb = EXP(-(intup(1)/cos1))*(1-eps)*tbb
  sumjub = tbb
  jupb = 0.0
  jdb = 0.0
  DO i=n+1,1,-1
    jupb(i) = jupb(i) + k(i)*dz*EXP(-(intup(i)/cos1))*sumjub/cos1
    jdb(i) = jdb(i) + k(i)*dz*EXP(-(intdo(i)/cos1))*sumjdb/cos1
  END DO
  i01pb = 0.0
  DO k1=n+1,1,-1
    tempb = -(a(k1)*g(k1)*cos1*0.5*jdb(k1))
    i01pb(2*k1) = i01pb(2*k1) + a(k1)*jdb(k1)
    i01pb(2*k1-1) = i01pb(2*k1-1) + tempb
    i01pb(2*k1+1) = i01pb(2*k1+1) + tempb
    jdb(k1) = 0.0
    tempb0 = a(k1)*g(k1)*cos1*0.5*jupb(k1)
    i01pb(2*k1-1) = i01pb(2*k1-1) + tempb0
    i01pb(2*k1+1) = i01pb(2*k1+1) + tempb0
    i01pb(2*k1) = i01pb(2*k1) + a(k1)*jupb(k1)
    jupb(k1) = 0.0
  END DO
  tbb = 0.0
END SUBROUTINE TBF90_BI

SUBROUTINE TBF90_Bk(tb, tbb, i01p, t, incang, k, kb, a, g, n, eps, dz)
  IMPLICIT NONE
  REAL :: incang, eps, dz
  INTEGER :: n
  REAL :: tb
  REAL :: tbb
  REAL :: k(n+1), a(n+1), g(n+1)
  REAL,intent(out) :: kb(n+1)
  REAL :: i01p(2*n+3)
  REAL :: jup(n+1), jd(n+1), t(n+1)
  REAL :: cos1
  REAL :: intdo(n+1)
  REAL :: intdob(n+1)
  REAL :: intup(n+1)
  REAL :: intupb(n+1)
  REAL :: pi, sumjd, sumju
  REAL :: sumjdb, sumjub
  INTEGER :: k1, i
  INTRINSIC COS
  INTRINSIC EXP
  REAL :: tempb
  REAL :: tempb0
  REAL :: temp
  REAL :: temp0
  REAL :: tempb1
  REAL :: tempb2
  REAL :: temp1
  pi = 3.1415
  jd = 0.
  jup = 0.
  cos1 = COS(incang/180.*pi)
  DO k1=1,n+1
    jup(k1) = (1-a(k1))*t(k1) + a(k1)*(0.5*(i01p(2*k1-1)+i01p(2*k1+1))*g&
&     (k1)*cos1+i01p(2*k1))
    jd(k1) = (1-a(k1))*t(k1) + a(k1)*(-(0.5*(i01p(2*k1-1)+i01p(2*k1+1))*&
&     g(k1)*cos1)+i01p(2*k1))
  END DO
  intdo(1) = k(1)*dz/2
  intup(n+1) = k(n+1)*dz/2
  DO k1=1,n
    intup(n+1-k1) = intup(n-k1+2) + 0.5*(k(n+1-k1)+k(n+1-k1+1))*dz
  END DO
  DO k1=2,n+1
    intdo(k1) = intdo(k1-1) + 0.5*(k(k1)+k(k1-1))*dz
  END DO
  sumjd = 0.
  DO i=1,n+1
    sumjd = sumjd + jd(i)*EXP(-(intdo(i)/cos1))*k(i)*dz/cos1
  END DO
  intupb = 0.0
  temp1 = -(intup(1)/cos1)
  intupb(1) = intupb(1) + (-(EXP(-(intup(1)/cos1))*eps*t(1)/cos1)-EXP(&
&   temp1)*sumjd*(1-eps)/cos1)*tbb
  sumjdb = (1-eps)*EXP(temp1)*tbb
  sumjub = tbb
  kb = 0.0
  intdob = 0.0
  DO i=n+1,1,-1
    tempb2 = jd(i)*dz*sumjdb
    temp = -(intdo(i)/cos1)
    temp0 = -(intup(i)/cos1)
    tempb1 = jup(i)*dz*sumjub
    intupb(i) = intupb(i) - EXP(temp0)*k(i)*tempb1/cos1**2
    kb(i) = kb(i) + EXP(temp)*tempb2/cos1 + EXP(temp0)*tempb1/cos1
    intdob(i) = intdob(i) - EXP(temp)*k(i)*tempb2/cos1**2
  END DO
  DO k1=n+1,2,-1
    tempb0 = dz*0.5*intdob(k1)
    intdob(k1-1) = intdob(k1-1) + intdob(k1)
    kb(k1) = kb(k1) + tempb0
    kb(k1-1) = kb(k1-1) + tempb0
    intdob(k1) = 0.0
  END DO
  DO k1=n,1,-1
    tempb = dz*0.5*intupb(n+1-k1)
    intupb(n-k1+2) = intupb(n-k1+2) + intupb(n+1-k1)
    kb(n+1-k1) = kb(n+1-k1) + tempb
    kb(n+1-k1+1) = kb(n+1-k1+1) + tempb
    intupb(n+1-k1) = 0.0
  END DO
  kb(n+1) = kb(n+1) + dz*intupb(n+1)/2
  kb(1) = kb(1) + dz*intdob(1)/2
  tbb = 0.0
END SUBROUTINE TBF90_Bk

SUBROUTINE TBF90_Bkag(tb, tbb, i01p, t, incang, k, kb, a, ab, g, gb, n, eps&
& , dz)
  IMPLICIT NONE
  REAL :: incang, eps, dz
  INTEGER :: n
  REAL :: tb
  REAL :: tbb
  REAL :: k(n+1), a(n+1), g(n+1)
  REAL,intent(out) :: kb(n+1), ab(n+1), gb(n+1)
  REAL :: i01p(2*n+3)
  REAL :: jup(n+1), jd(n+1), t(n+1)
  REAL :: jupb(n+1), jdb(n+1)
  REAL :: cos1
  REAL :: intdo(n+1)
  REAL :: intdob(n+1)
  REAL :: intup(n+1)
  REAL :: intupb(n+1)
  REAL :: pi, sumjd, sumju
  REAL :: sumjdb, sumjub
  INTEGER :: k1, i
  INTRINSIC COS
  INTRINSIC EXP
  REAL :: temp
  REAL :: temp0
  REAL :: tempb
  REAL :: tempb0
  REAL :: temp1
  REAL :: temp2
  REAL :: temp3
  REAL :: temp4
  REAL :: tempb1
  REAL :: tempb2
  REAL :: temp5
  pi = 3.1415
  jd = 0.
  jup = 0.
  cos1 = COS(incang/180.*pi)
  DO k1=1,n+1
    jup(k1) = (1-a(k1))*t(k1) + a(k1)*(0.5*(i01p(2*k1-1)+i01p(2*k1+1))*g&
&     (k1)*cos1+i01p(2*k1))
    jd(k1) = (1-a(k1))*t(k1) + a(k1)*(-(0.5*(i01p(2*k1-1)+i01p(2*k1+1))*&
&     g(k1)*cos1)+i01p(2*k1))
  END DO
  intdo(1) = k(1)*dz/2
  intup(n+1) = k(n+1)*dz/2
  DO k1=1,n
    intup(n+1-k1) = intup(n-k1+2) + 0.5*(k(n+1-k1)+k(n+1-k1+1))*dz
  END DO
  DO k1=2,n+1
    intdo(k1) = intdo(k1-1) + 0.5*(k(k1)+k(k1-1))*dz
  END DO
  sumjd = 0.
  DO i=1,n+1
    sumjd = sumjd + jd(i)*EXP(-(intdo(i)/cos1))*k(i)*dz/cos1
  END DO
  intupb = 0.0
  temp5 = -(intup(1)/cos1)
  intupb(1) = intupb(1) + (-(EXP(-(intup(1)/cos1))*eps*t(1)/cos1)-EXP(&
&   temp5)*sumjd*(1-eps)/cos1)*tbb
  sumjdb = (1-eps)*EXP(temp5)*tbb
  sumjub = tbb
  kb = 0.0
  intdob = 0.0
  jupb = 0.0
  jdb = 0.0
  DO i=n+1,1,-1
    temp1 = -(intdo(i)/cos1)
    temp2 = jd(i)/cos1
    tempb2 = dz*EXP(temp1)*sumjdb
    temp3 = -(intup(i)/cos1)
    temp4 = jup(i)/cos1
    tempb1 = dz*EXP(temp3)*sumjub
    jupb(i) = jupb(i) + k(i)*tempb1/cos1
    kb(i) = kb(i) + temp2*tempb2 + temp4*tempb1
    intupb(i) = intupb(i) - EXP(temp3)*temp4*k(i)*dz*sumjub/cos1
    jdb(i) = jdb(i) + k(i)*tempb2/cos1
    intdob(i) = intdob(i) - EXP(temp1)*temp2*k(i)*dz*sumjdb/cos1
  END DO
  DO k1=n+1,2,-1
    tempb0 = dz*0.5*intdob(k1)
    intdob(k1-1) = intdob(k1-1) + intdob(k1)
    kb(k1) = kb(k1) + tempb0
    kb(k1-1) = kb(k1-1) + tempb0
    intdob(k1) = 0.0
  END DO
  DO k1=n,1,-1
    tempb = dz*0.5*intupb(n+1-k1)
    intupb(n-k1+2) = intupb(n-k1+2) + intupb(n+1-k1)
    kb(n+1-k1) = kb(n+1-k1) + tempb
    kb(n+1-k1+1) = kb(n+1-k1+1) + tempb
    intupb(n+1-k1) = 0.0
  END DO
  kb(n+1) = kb(n+1) + dz*intupb(n+1)/2
  kb(1) = kb(1) + dz*intdob(1)/2
  gb = 0.0
  ab = 0.0
  DO k1=n+1,1,-1
    temp = i01p(2*k1-1) + i01p(2*k1+1)
    temp0 = i01p(2*k1-1) + i01p(2*k1+1)
    ab(k1) = ab(k1) + (i01p(2*k1)+temp*(cos1*0.5*g(k1))-t(k1))*jupb(k1) &
&     + (i01p(2*k1)-temp0*(cos1*0.5*g(k1))-t(k1))*jdb(k1)
    gb(k1) = gb(k1) + temp*a(k1)*cos1*0.5*jupb(k1) - temp0*a(k1)*cos1*&
&     0.5*jdb(k1)
    jdb(k1) = 0.0
    jupb(k1) = 0.0
  END DO
  tbb = 0.0
END SUBROUTINE TBF90_BKAG


SUBROUTINE TBF90_EPS_B(tb, tbb, i01p, t, incang, k, a, g, n, eps, epsb, &
& dz)
  IMPLICIT NONE
  REAL :: incang, eps, dz
  REAL,intent(out) :: epsb
  INTEGER :: n
  REAL :: tb
  REAL :: tbb
  REAL :: k(n+1), a(n+1), g(n+1)
  REAL :: i01p(2*n+3)
  REAL :: jup(n+1), jd(n+1), t(n+1)
  REAL :: cos1
  REAL :: intdo(n+1)
  REAL :: intup(n+1)
  REAL :: pi, sumjd, sumju
  INTEGER :: k1, i
  INTRINSIC COS
  INTRINSIC EXP
  pi = 3.1415
  jd = 0.
  cos1 = COS(incang/180.*pi)
  DO k1=1,n+1
    jd(k1) = (1-a(k1))*t(k1) + a(k1)*(-(0.5*(i01p(2*k1-1)+i01p(2*k1+1))*&
&     g(k1)*cos1)+i01p(2*k1))
  END DO
  intdo(1) = k(1)*dz/2
  intup(n+1) = k(n+1)*dz/2
  DO k1=1,n
    intup(n+1-k1) = intup(n-k1+2) + 0.5*(k(n+1-k1)+k(n+1-k1+1))*dz
  END DO
  DO k1=2,n+1
    intdo(k1) = intdo(k1-1) + 0.5*(k(k1)+k(k1-1))*dz
  END DO
  sumjd = 0.
  DO i=1,n+1
    sumjd = sumjd + jd(i)*EXP(-(intdo(i)/cos1))*k(i)*dz/cos1
  END DO
  epsb = (t(1)*EXP(-(intup(1)/cos1))-sumjd*EXP(-(intup(1)/cos1)))*tbb
  tbb = 0.0
END SUBROUTINE TBF90_EPS_B


!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 31 May 2021 11:17
!
!  Differentiation of suml1al2_eps in reverse (adjoint) mode:
!   gradient     of useful results: y
!   with respect to varying inputs: y eps
!   RW status of diff variables: y:in-zero eps:out
SUBROUTINE SUML1AL2_EPS_B(y, yb, lam1, lam2, k, a, g, n, t, eps, epsb, abigb, &
     dz)
  IMPLICIT NONE
  INTEGER :: n
  REAL :: y, lam1(2*n+3), lam2(2*n+3), k(n+1), a(n+1), g(n+1), t(n+1), &
& dz, eps
  REAL :: yb
  real, intent(out) :: epsb
  REAL :: abig(2*n+3, 2*n+3), am, km, gm
  REAL,intent(out) :: abigb(2*n+3, 2*n+3)
  INTEGER :: i
  REAL :: tempb
  abigb = 0.0
  abigb(1, 3) = abigb(1, 3) + lam1(1)*lam2(3)*yb
  abigb(1, 1) = abigb(1, 1) + lam1(1)*lam2(1)*yb
  tempb = abigb(1, 3)/(3.*eps)
  abigb(1, 3) = 0.0
  epsb = -(((2-eps)/eps+1.0)*tempb)
  abigb(1, 2) = 0.0
  tempb = abigb(1, 1)/(3.*eps)
  epsb = epsb - ((2-eps)/eps+1.0)*tempb
  yb = 0.0
END SUBROUTINE SUML1AL2_EPS_B
