SUBROUTINE RADTRAN_py(UMU, NLYR, TB, BTEMP, LYRTEMP, LYRHGT, KEXT, &
     SALB, ASYM, FISOT, EMIS, EBAR, LAMBERT)
  implicit none  
  real, intent(out) :: tb


  INTEGER *4 MAXLYR
  PARAMETER    ( MAXLYR = 190 )
  
  CHARACTER*1  POLN
  LOGICAL LAMBERT, PRNT(3)
  integer ier, imode, icode
  INTEGER NLYR, I, J, NANG, NN
  REAL::  UMU, BTEMP, LYRTEMP(0:NLYR), LYRHGT(0:NLYR), &
       KEXT(NLYR), SALB(NLYR), ASYM(NLYR), fisot,emis,ebar

  call RADTRAN(UMU, NLYR, TB, BTEMP, LYRTEMP, LYRHGT, KEXT, &
       SALB, ASYM, FISOT, EMIS, EBAR, LAMBERT)

end SUBROUTINE RADTRAN_py
